### ISSUE TITLE
translate fail "throw new ERR_INVALID_ARG_TYPE(name, 'Function', value);"

### ISSUE THREAD

**Issue by haedoang** [zhangjingcn/xmind-markdown-translator#5]
translate fail throw following error  

TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at makeCallback (node:fs:195:3)
    at Object.mkdir (node:fs:1357:14)
    at attachmentWriter (/Users/haedongkim/Desktop/dev/xmind-markdown-translator/lib/attachmentWriter.js:13:12)
    at Object.<anonymous> (/Users/haedongkim/Desktop/dev/xmind-markdown-translator/app.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at loader (/Users/haedongkim/Desktop/dev/xmind-markdown-translator/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/Users/haedongkim/Desktop/dev/xmind-markdown-translator/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {

**Comment by haedoang** [comment]
node version : v18.12.1

**Comment by Sergey-Titkov** [comment]
This is old code and did not work with file after XMind 8

**Comment by soldi1060** [comment]
So what can we do?
